apiVersion: v1
kind: Service
metadata:
  name: moodle-mysql
  labels:
    app: moodle-mysql
spec:
  ports:
    - port: 3306
      nodePort: 32000
  selector:
    app: moodle-mysql
  type: NodePort
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  labels:
    app: moodle-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: moodle-mysql
  labels:
    app: moodle-mysql
spec:
  selector:
    matchLabels:
      app: moodle-mysql
  template:
    metadata:
      labels:
        app: moodle-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password1
        - name: MYSQL_DATABASE
          value: moodle
        - name: MYSQL_USER
          value: user1
        - name: MYSQL_PASSWORD
          value: password1
        ports:
        - containerPort: 3306
          name: mysql
        readinessProbe:
          exec:
            command: ["/bin/sh", "-i", "-c", "MYSQL_PWD=\"$MYSQL_PASSWORD\" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE -e 'SELECT 1'"]
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-data
---