apiVersion: moodlecontroller.kubeplus/v1
kind: Moodle
metadata:
  name: moodle1
spec:
  plugins: ["profilecohort"]
  mySQLServiceName: my-cluster-mysql-master
  mySQLUserName: root
  mySQLUserPassword: mypass
  moodleAdminEmail: test@test.com
